package com.example.test2.framework.data.database

import android.content.Context
import com.example.test2.data.entities.implementations.MyObjectBox
import io.objectbox.BoxStore

object ObjectBox {
    lateinit var mBoxStore: BoxStore
        private set

    fun init(context: Context) {
        //MyObjectBox is generated by io.objectbox
        //package points to entities
        mBoxStore = MyObjectBox.builder()
            .androidContext(context.applicationContext)
            .build()
    }
}